name: github pages

on:
  push:
    branches:
    - master
    tags:
    - 'v*.*.*'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - run: yarn install

    - run: yarn build

    - run: yarn export

    - run: touch ./out/.nojekyll

    - name: Prepare tag
      id: prepare_tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        TAG_NAME="${GITHUB_REF##refs/tags/}"
        # TAG_NAME="v$(jq -r '.version' ./package.json)"
        echo "::set-output name=tag_name::deploy-${TAG_NAME}"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@feat-tagname-option
      # uses: docker://peaceiris/gh-pages:v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./out
      with:
        tagName: ${{ steps.prepare_tag.outputs.tag_name }}
        tagMessage: 'Deploy ${{ steps.prepare_tag.outputs.tag_name }}'
      #   username: "iris"
      #   useremail: "iris@peaceiris.com"
      #   forceOrphan: true

#    - name: Deploy (script)
#      env:
#        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        PUBLISH_BRANCH: gh-pages
#        PUBLISH_DIR: ./out
#        SCRIPT_MODE: true
#        INPUT_FORCEORPHAN: true
#      run: |
#        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
#        bash ./entrypoint.sh
